const products=[{name:'The Cherry Shoulder Bag',price:1890,image:'assets/bag.webp',description:'A rich cherry shade, chunky crochet texture and a soft curved silhouette. An everyday shoulder bag with a little personality.'},{name:'The Forever Bloom',price:390,image:'assets/flowers.webp',description:'A small ivory bloom, stitched petal by petal. A thoughtful little keepsake for a desk, a shelf or someone special.'}];
const money=n=>'₹'+n.toLocaleString('en-IN');let selected=0;let cart=[];try{cart=JSON.parse(sessionStorage.getItem('pris-cozy-bag')||'[]').filter(n=>n===0||n===1)}catch{}const detail=document.querySelector('#product-dialog'),bag=document.querySelector('#bag-dialog');document.querySelector('#year').textContent=new Date().getFullYear();
document.querySelectorAll('[data-product]').forEach(b=>b.addEventListener('click',()=>{selected=Number(b.dataset.product);const p=products[selected];document.querySelector('#detail-image').src=p.image;document.querySelector('#detail-image').alt=p.name;document.querySelector('#detail-title').textContent=p.name;document.querySelector('#detail-description').textContent=p.description;document.querySelector('#detail-price').textContent=money(p.price);document.querySelector('#added-message').textContent='';detail.showModal()}));
document.querySelectorAll('dialog .close').forEach(b=>b.addEventListener('click',()=>b.closest('dialog').close()));document.querySelectorAll('dialog').forEach(d=>d.addEventListener('click',e=>{if(e.target===d){const r=d.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)d.close()}}));
function update(){document.querySelector('#count').textContent=cart.length;try{sessionStorage.setItem('pris-cozy-bag',JSON.stringify(cart))}catch{}}
document.querySelector('#add-bag').addEventListener('click',()=>{cart.push(selected);update();document.querySelector('#added-message').textContent='Added to your bag.'});
function renderBag(){const list=document.querySelector('#bag-items');list.replaceChildren();if(!cart.length){const p=document.createElement('p');p.textContent='Your bag is waiting for something lovely.';list.append(p)}cart.forEach((index,i)=>{const p=products[index];const row=document.createElement('div');row.className='bag-row';const img=document.createElement('img');img.src=p.image;img.alt=p.name;const info=document.createElement('div');const title=document.createElement('p');title.textContent=p.name;const price=document.createElement('p');price.textContent=money(p.price);info.append(title,price);const remove=document.createElement('button');remove.textContent='Remove';remove.setAttribute('aria-label','Remove '+p.name);remove.onclick=()=>{cart.splice(i,1);update();renderBag()};row.append(img,info,remove);list.append(row)});document.querySelector('#bag-total').textContent=cart.length?'Subtotal: '+money(cart.reduce((n,i)=>n+products[i].price,0)):''}
document.querySelector('#open-bag').onclick=()=>{renderBag();bag.showModal()};document.querySelector('#continue').onclick=()=>{bag.close();document.querySelector('#collection').scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth'})};update();
if(!matchMedia('(prefers-reduced-motion: reduce)').matches&&'IntersectionObserver'in window){const observer=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.animate([{opacity:0,transform:'translateY(20px)'},{opacity:1,transform:'translateY(0)'}],{duration:700,easing:'cubic-bezier(.2,.7,.2,1)'});observer.unobserve(e.target)}}),{threshold:.15});document.querySelectorAll('.reveal').forEach(e=>observer.observe(e))}
let category='all',wishOnly=false;let wishes=[];try{wishes=JSON.parse(localStorage.getItem('pris-wishlist')||'[]').filter(n=>n===0||n===1)}catch{}
const search=document.querySelector('#shop-search');let budget='all',priceLimit=2000;function applyFilters(){const query=search.value.trim().toLowerCase();let count=0;document.querySelectorAll('.product').forEach(el=>{const id=Number(el.dataset.id),p=products[id];el.hidden=!(category==='all'||el.dataset.category===category)||!(p.name+' '+p.description).toLowerCase().includes(query)||(wishOnly&&!wishes.includes(id))||(budget!=='all'&&p.price>=Number(budget))||p.price>priceLimit;if(!el.hidden)count++});document.querySelector('#results-status').textContent=count+(count===1?' piece':' pieces')+(wishOnly?' in your wishlist':' to discover');document.querySelector('.empty-results').hidden=count>0;document.querySelectorAll('[data-budget]').forEach(b=>{const active=b.dataset.budget===budget;b.classList.toggle('active',active);b.setAttribute('aria-pressed',active)});const filters=(category!=='all'?1:0)+(budget!=='all'?1:0)+(wishOnly?1:0);document.querySelector('#filter-count').hidden=!filters;document.querySelector('#filter-count').textContent=filters;document.querySelectorAll('[data-filter]').forEach(b=>{const active=b.dataset.filter===category;b.classList.toggle('active',active);b.setAttribute('aria-pressed',active)})}
function browse(cat){document.querySelectorAll('dialog[open]').forEach(d=>d.close());category=cat;budget='all';priceLimit=2000;wishOnly=false;search.value='';applyFilters();document.querySelector('#collection').scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth'})}
document.querySelectorAll('[data-filter]').forEach(b=>b.onclick=()=>{category=b.dataset.filter;wishOnly=false;applyFilters()});document.querySelectorAll('[data-category-link]').forEach(b=>b.onclick=()=>browse(b.dataset.categoryLink));document.querySelector('#reset-search').onclick=()=>browse('all');document.querySelector('#sort-products').onchange=e=>{const els=[...document.querySelectorAll('.product')];els.sort((a,b)=>{const ai=Number(a.dataset.id),bi=Number(b.dataset.id);return e.target.value==='low'?products[ai].price-products[bi].price:e.target.value==='high'?products[bi].price-products[ai].price:ai-bi});els.forEach(el=>document.querySelector('.products').append(el))};
function syncWishes(){document.querySelector('#wish-count').textContent=wishes.length;document.querySelectorAll('[data-save]').forEach(b=>{const saved=wishes.includes(Number(b.dataset.save));b.setAttribute('aria-pressed',saved);b.querySelector('svg').setAttribute('fill',saved?'currentColor':'none')});try{localStorage.setItem('pris-wishlist',JSON.stringify(wishes))}catch{}}
document.querySelectorAll('[data-save]').forEach(b=>b.onclick=()=>{const id=Number(b.dataset.save);wishes=wishes.includes(id)?wishes.filter(n=>n!==id):[...wishes,id];syncWishes();applyFilters()});document.querySelector('#show-wishlist').onclick=()=>{category='all';budget='all';search.value='';wishOnly=true;applyFilters();document.querySelector('#collection').scrollIntoView({behavior:'smooth'})};document.querySelectorAll('[data-gift]').forEach(b=>b.onclick=()=>{browse(b.dataset.gift==='bags'?'bags':b.dataset.gift==='under'?'flowers':'all')});syncWishes();applyFilters();
const banners=[...document.querySelectorAll('.banner')],dots=[...document.querySelectorAll('.slide-dots button')],carousel=document.querySelector('.carousel');const reduced=matchMedia('(prefers-reduced-motion: reduce)');let slide=0,frame=0,elapsed=0,lastTime=0,dragging=false;const revealDelay=350,charDelay=12,holdDuration=3000;
const slideText=banners.map(b=>{const elements=[b.querySelector('h1'),b.querySelector('p')];return elements.map(el=>({el,nodes:[...(()=>{const walker=document.createTreeWalker(el,NodeFilter.SHOW_TEXT);let n,arr=[];while(n=walker.nextNode())arr.push(n);return arr})()].map(node=>({node,text:node.textContent}))}))});
function restoreText(){slideText.forEach(parts=>parts.forEach(part=>{part.nodes.forEach(n=>n.node.textContent=n.text);part.el.classList.remove('typing-caret');part.el.style.minHeight=''}))}
function lengthOf(index){return slideText[index].reduce((sum,p)=>sum+p.nodes.reduce((n,t)=>n+t.text.length,0),0)}
function typeAt(count){let left=count;slideText[slide].forEach(part=>{const length=part.nodes.reduce((n,t)=>n+t.text.length,0);part.nodes.forEach(n=>{const take=Math.max(0,Math.min(left,n.text.length));n.node.textContent=n.text.slice(0,take);left-=take});part.el.classList.toggle('typing-caret',count>0&&left===0&&part.nodes.some(n=>n.node.textContent.length<n.text.length));count-=length})}
function showSlide(index){cancelAnimationFrame(frame);restoreText();slide=(index+banners.length)%banners.length;banners.forEach((b,i)=>{b.hidden=i!==slide;b.classList.toggle('active',i===slide)});dots.forEach((b,i)=>{b.classList.toggle('selected',i===slide);b.setAttribute('aria-pressed',i===slide);b.querySelector('.dot-fill').style.transform='scaleX(0)'});elapsed=0;lastTime=0;if(reduced.matches){dots[slide].querySelector('.dot-fill').style.transform='scaleX(1)';return}slideText[slide].forEach(part=>{part.el.style.minHeight=part.el.getBoundingClientRect().height+'px';part.el.setAttribute('aria-label',part.nodes.map(n=>n.text).join(''));part.nodes.forEach(n=>n.node.textContent='')});banners[slide].querySelector('img').animate([{opacity:.35,transform:'translateY(8px)'},{opacity:1,transform:'translateY(0)'}],{duration:350,easing:'ease-out'});frame=requestAnimationFrame(tick)}
function tick(time){if(document.hidden||dragging){lastTime=0;frame=0;return}if(lastTime)elapsed+=Math.min(time-lastTime,80);lastTime=time;const typingDuration=lengthOf(slide)*charDelay,total=revealDelay+typingDuration+holdDuration;typeAt(Math.floor(Math.max(0,elapsed-revealDelay)/charDelay));dots[slide].querySelector('.dot-fill').style.transform='scaleX('+Math.min(elapsed/total,1)+')';if(elapsed>=total){showSlide(slide+1);return}frame=requestAnimationFrame(tick)}
function resume(){if(!document.hidden&&!dragging&&!reduced.matches&&!frame){lastTime=0;frame=requestAnimationFrame(tick)}}document.querySelector('#next-slide').onclick=()=>showSlide(slide+1);document.querySelector('#prev-slide').onclick=()=>showSlide(slide-1);dots.forEach((b,i)=>b.onclick=()=>showSlide(i));document.addEventListener('visibilitychange',()=>{if(document.hidden){cancelAnimationFrame(frame);frame=0;lastTime=0}else resume()});let touchX=0;carousel.addEventListener('touchstart',e=>{touchX=e.changedTouches[0].clientX;dragging=true;cancelAnimationFrame(frame);frame=0;lastTime=0},{passive:true});carousel.addEventListener('touchend',e=>{dragging=false;const delta=e.changedTouches[0].clientX-touchX;if(Math.abs(delta)>50)showSlide(slide+(delta<0?1:-1));else resume()},{passive:true});carousel.addEventListener('touchcancel',()=>{dragging=false;resume()},{passive:true});reduced.addEventListener('change',()=>showSlide(slide));showSlide(0);
const filterDialog=document.querySelector('#filter-dialog'),searchDialog=document.querySelector('#search-dialog'),supportDialog=document.querySelector('#support-dialog');document.querySelectorAll('[data-budget]').forEach(b=>b.onclick=()=>{budget=b.dataset.budget;wishOnly=false;applyFilters()});document.querySelector('#open-search').onclick=()=>{searchDialog.showModal();search.focus()};document.querySelector('#product-search-form').onsubmit=e=>{e.preventDefault();category='all';budget='all';wishOnly=false;applyFilters();searchDialog.close();document.querySelector('#collection').scrollIntoView({behavior:reduced.matches?'auto':'smooth'})};document.querySelector('#open-support').onclick=()=>supportDialog.showModal();document.querySelectorAll('[data-support-target]').forEach(b=>b.onclick=()=>{supportDialog.close();document.querySelector('#info-'+b.dataset.supportTarget).showModal()});

document.querySelector('#sort-products').value='low';document.querySelector('#sort-products').dispatchEvent(new Event('change'));

document.querySelectorAll('[data-info]').forEach(b=>b.onclick=()=>document.querySelector('#info-'+b.dataset.info).showModal());document.querySelectorAll('a[href="#story"],a[href="#care"],a[href="#gifting"],a[href="#faq"]').forEach(a=>a.addEventListener('click',e=>{e.preventDefault();document.querySelectorAll('dialog[open]').forEach(d=>d.close());document.querySelector('#info-'+a.getAttribute('href').slice(1)).showModal();document.querySelector('.menu').setAttribute('aria-expanded','false')}));

const menuDrawer=document.querySelector('#menu-drawer');document.querySelector('.menu').onclick=()=>{menuDrawer.showModal();document.querySelector('.menu').setAttribute('aria-expanded','true')};menuDrawer.addEventListener('close',()=>document.querySelector('.menu').setAttribute('aria-expanded','false'));document.querySelectorAll('[data-drawer-shop]').forEach(b=>b.onclick=()=>{menuDrawer.close();browse(b.dataset.drawerShop)});document.querySelectorAll('[data-drawer-info]').forEach(b=>b.onclick=()=>{menuDrawer.close();document.querySelector('#info-'+b.dataset.drawerInfo).showModal()});
const range=document.querySelector('#price-limit');function paintRange(){document.querySelector('#price-value').textContent=money(Number(range.value));range.style.setProperty('--range-fill',(Number(range.value)/20)+'%')}range.oninput=paintRange;document.querySelector('#open-filters').onclick=()=>{document.querySelectorAll('[name=category]').forEach(x=>x.checked=x.value===category);range.value=priceLimit;document.querySelector('#saved-only').checked=wishOnly;document.querySelector('#filter-sort').value=document.querySelector('#sort-products').value;paintRange();filterDialog.showModal()};document.querySelector('#apply-filters').onclick=()=>{category=document.querySelector('[name=category]:checked').value;priceLimit=Number(range.value);budget='all';wishOnly=document.querySelector('#saved-only').checked;const sort=document.querySelector('#sort-products');sort.value=document.querySelector('#filter-sort').value;sort.dispatchEvent(new Event('change'));applyFilters();filterDialog.close();document.querySelector('#collection').scrollIntoView({behavior:reduced.matches?'auto':'smooth'})};document.querySelector('#reset-filters').onclick=()=>{document.querySelector('[name=category][value=all]').checked=true;range.value=2000;document.querySelector('#saved-only').checked=false;document.querySelector('#filter-sort').value='low';paintRange()};paintRange();
